"""
Mock data and fake responses used in --mock mode and tests.

Keeping all mock fixtures here makes it easy to update them without
touching business-logic code.
"""

MOCK_WEATHER: dict[str, dict] = {
    "london": {
        "city": "London",
        "temperature_celsius": 14,
        "condition": "Partly cloudy",
        "humidity_percent": 72,
        "wind_kmh": 18,
        "summary": "Mild and partly cloudy in London. Bring a light jacket.",
    },
    "new york": {
        "city": "New York",
        "temperature_celsius": 22,
        "condition": "Sunny",
        "humidity_percent": 55,
        "wind_kmh": 12,
        "summary": "Sunny and warm in New York. Great day to be outside.",
    },
    "tokyo": {
        "city": "Tokyo",
        "temperature_celsius": 18,
        "condition": "Light rain",
        "humidity_percent": 85,
        "wind_kmh": 8,
        "summary": "Light rain in Tokyo. An umbrella is recommended.",
    },
}

MOCK_CODE_RESPONSE = '''"""Generated by vibe-agentic-ai (mock mode)."""


def solution(input_data):
    """
    Mock implementation — replace with real Claude output in non-mock mode.

    This stub demonstrates the shape of code the agent would generate.
    """
    # TODO: implement the actual logic here
    return f"Processed: {input_data}"


if __name__ == "__main__":
    print(solution("hello world"))
'''

MOCK_CODE_REVIEW = (
    "Mock code review (mock mode):\n"
    "- No syntax errors detected\n"
    "- Docstring present — good!\n"
    "- Consider adding type hints for production use\n"
    "- Add unit tests before shipping"
)


def get_mock_weather(city: str) -> dict:
    """Return mock weather data for *city*, falling back to a generic response."""
    return MOCK_WEATHER.get(
        city.lower(),
        {
            "city": city,
            "temperature_celsius": 20,
            "condition": "Clear",
            "humidity_percent": 60,
            "wind_kmh": 10,
            "summary": f"Pleasant weather in {city}.",
        },
    )
